baseURL = 'http://pol.odyssey346.dev'
languageCode = 'en-us'
title = 'Odyssey346 Poland VPS'
theme = 'm1n1m4l'
description = 'Where I host my instances n stuff™️'
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[languages]
  [languages.en]
    footer = "Served by <a href=\"https://caddyserver.com\" target=\"_blank\""
