baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Odyssey346 Poland VPS'
theme = 'instances'
description = 'Where I host my instances n stuff™️'
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
