name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: "Install theme"
        run: git clone https://github.com/Odyssey346/hugo-theme-m1n1m4l themes/m1n1m4l

      - name: Build
        run: hugo --minify

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
            branch: build # The branch the action should deploy to.
            folder: public # The folder the action should deploy.
            commit-message: Successfully built
            clean: true
            single-commit: false